id: I5E44B944
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:27:40.412463
last_modified: 2023-02-08 15:27:40.412553
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  E080:
    base_file: E080.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
